### ISSUE TITLE
Scraper BeautifulSoup failure

### ISSUE THREAD

**Issue by swglad** [sourcemash/Sourcemash#265]
Traceback (most recent call last):
  File "manage.py", line 153, in <module>
    manager.run()
  File "/Users/scottgladstone/Sourcemash/flask/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/Users/scottgladstone/Sourcemash/flask/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/Users/scottgladstone/Sourcemash/flask/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 98, in feed_seed
    scrape_and_categorize_articles()
  File "/Users/scottgladstone/Sourcemash/worker/scraper.py", line 26, in scrape_and_categorize_articles
    scrape_feed_articles(feed)
  File "/Users/scottgladstone/Sourcemash/worker/scraper.py", line 57, in scrape_feed_articles
    img_url = soup.find('img')['src']
TypeError: <flask_script.commands.Command object at 0x10b221250>: 'NoneType' object has no attribute '__getitem__'

**Comment by swglad** [comment]
Duplicate of #263.
